### ISSUE TITLE
Neo4j-desktop deletes databases when projects are deleted. Should move to trash.

### ISSUE THREAD

**Issue by graphadvantage** [neo4j-apps/neo4j-desktop#1]
Hi

There is a workflow issue with neo4j-desktop, which is that deleting a project (which anyone can do) also irrevocably deletes the associated databases and all of the configurations, import directory files etc. Given that a project is just a wrapper with no roles this seems risky.

A better approach would be copy deleted projects and databases to a /trash folder, where they could be retrieved if needed or permanently deleted one by one.

-Thanks
Michael

**Comment by FylmTM** [comment]
@graphadvantage 

Thanks for the feedback!
This sound like an interesting idea.

Can you describe a use case, where you need to keep a database while removing a project?
Also, can we cover such use cases if we implement database moving/copying functionality, and leaving project deletion as is?

**Comment by graphadvantage** [comment]
I think it's more a best practices issue, a recursive delete allows for unintended consequences.

We are using desktop as a launch pad for demos and tests, sometimes there are multiple databases in a project.

**Comment by akollegger** [comment]
This issue is no longer relevant for the current release of Neo4j Desktop 1.3.4. Notably, Desktop is moving steadily in a direction to decouple the life of a project and the life of DBMSes. Initially, projects had a strong "ownership" of DBMSes, but we're moving away from that to projects referring to DBMSes. 

Please re-open this issue if it becomes relevant again.
