### ISSUE TITLE
neo4j-desktop segmentation fault when trying to start on Ubuntu 18.10

### ISSUE THREAD

**Issue by kaerumy** [neo4j-apps/neo4j-desktop#37]
- Neo4j version: neo4j-desktop-1.1.10-x86_64.AppImage
- Operating system: Ubuntu 18.10

Segmentation fault when trying to start
### Steps to reproduce

1. Start existing or newly downloaded App Image 

~/dev$ ./neo4j-desktop-1.1.10-x86_64.AppImage

### Expected behavior
neo4j Desktop starts and opens
### Actual behavior
Segmentation fault (core dumped)

**Comment by P1zz4br0etch3n** [comment]
I also face this issue after upgrading Fedora 28 to 29. Before that it worked fine.

**Comment by P1zz4br0etch3n** [comment]
It might be something websocket related, because I also face problems in browsing our Neo4j VMs via HTTP from my machine. I can open the Neo4j Browser via `<hostname>:7474/browser` but I can't connect to the database. When i try to connect with username and password (which are correct) I get following error: `ServiceUnavailable: WebSocket connection failure.`

The development console says something like: `Can't connect to server ws://<hostname>:7687`

Same in Chrome and Firefox.
On a Fedora 28 machine everything works fine.

**Comment by P1zz4br0etch3n** [comment]
Error is gone for me with `neo4j-desktop-offline-1.1.13-x86_64.AppImage`

**Comment by mattcasters** [comment]
Same for me, error is gone.

**Comment by Metaur** [comment]
@P1zz4br0etch3n @mattcasters Thanks for the feedback, guys! It seems that the fresh electron version did resolve your issue, so I'll close this one.
