### ISSUE TITLE
Can't run Neo4j Desktop after installation

### ISSUE THREAD

**Issue by jexp** [neo4j-apps/neo4j-desktop#46]
https://community.neo4j.com/t/cant-run-neo4j-desktop-after-instalation/4839

After downloading and installing Neo4j Desktop 1.1.14 I open it the first time and the message below pops up.

%D0%91%D0%B5%D0%B7%D1%8B%D0%BC%D1%8F%D0%BD%D0%BD%D1%8B%D0%B9Безымянный.png786×573 12.1 KB
When press "Confirm" nothing happens.
Tried to run Neo4j Desktop as well as reinstall it as Admin - the same result.

OS: Windows 10 corporate v. 1607 build 14393.1489

The log file

**Comment by Metaur** [comment]
@jexp the issue is that user has corrupted PATH env variable. 
First, he needs to check if the `wmic.exe` is present in `C:\windows\system32\wbem` directory.
If true - add that path to env variable PATH. 
If not - use system-wide search to find that executable. it should be somewhere inside Windows folder.

**Comment by VladislavKutas** [comment]
> @jexp the issue is that user has corrupted PATH env variable.
> First, he needs to check if the `wmic.exe` is present in `C:\windows\system32\wbem` directory.
> If true - add that path to env variable PATH.
> If not - use system-wide search to find that executable. it should be somewhere inside Windows folder.

Thanks! It it helped!

**Comment by Metaur** [comment]
@VladislavKutas good to hear that!
