### ISSUE TITLE
Cannot install any 

### ISSUE THREAD

**Issue by aaramg** [neo4j-apps/neo4j-desktop#84]
![image](https://user-images.githubusercontent.com/20701693/80867945-3d5b2800-8ca8-11ea-8a63-bae85c36efe1.png)
Cannot install another plugin except APOC. They are disabled.
I use Neo4j 4.0.3

**Comment by akollegger** [comment]
Hi @aaramg ,

I suspect this is because there aren't compatible versions of those plugins available for the Neo4j 4.0.3. We should add clear messaging that explains why the plugins are not available.

- the "Graph Data Science Library" has been updated. that should now be available for install.
- "Graph Algorithms" is a deprecated library, which may not get updated
- "GraphQL" has not yet been updated

-Andreas
